import os
from dotenv import load_dotenv

### CONSTANTS ###

load_dotenv()
TOKEN = os.getenv('DISCORD_TOKEN')
GUILD = os.getenv('DISCORD_GUILD')

COMMANDS_PREFIX = "!"

MASTER_OF_THE_GAME = 'Maitre du jeu'


GAME_CATEGORY_NAME = "Neyqoh_Game"
GAME_VOICE_CHANNEL_NAME = "Place du village"
TEMP_VOICE_CHANNEL_NAME = "Voice"
HISTORY_TEXT_CHANNEL_NAME = "Histoire"
PRIVATE_TEXT_CHANNEL_NAME = 'Ton role et actions'
LOUPS_TEXT_CHANNEL_NAME = 'Loups Garous'
DEADS_TEXT_CHANNEL = 'Morts'

TIME_FOR_ROLES_REVEAL = 30
TIME_BETWEEN_TURNS = 2
TIME_FOR_LOUPS = 30
TIME_FOR_LOUP_BLANC = 30
TIME_FOR_MAYOR_ELECTION = 60  # TODO: 120 in prod

TIME_FOR_VICTIM_ELECTION = 120  # TODO: 120 in prod
TIME_FOR_MAYOR_FINAL_CHOICE = 30  # TODO: 10 - 20 secs in prod

TIME_FOR_MAYOR_GIVE_UP = 30  # TODO in prod 30 s

TIME_FOR_CUPIDON = 30

TIME_FOR_ENFANT_SAUVAGE = 30

TIME_FOR_VOYANTE = 30  # TODO 20 - 30 secs in prod

TIME_FOR_SALVATEUR = 30  # TODO 20-30 secs in prod

TIME_FOR_SORCIERE = 30

TIME_FOR_CHASSEUR = 30

TIME_DELETE_MSG = 0

TIME_AUTO_DESTRUCT = 60  # TODO: 30 in prod

NB_MAX_MAYOR_ELECTIONS = 3

#NB_MAX_VICTIM_ELECTIONS = 3

MINIMUM_PLAYER_NB = 2  # TODO: in prod : 4 players min

DEFAULT_NB_LOUP = 1  # if nb < nb_players => nb  else => nb = nb_players/4

DEFAULT_NB_LOUP_BLANC = 0

DEFAULT_NB_CUPIDON = 0

DEFAULT_NB_VOYANTE = 0

DEFAULT_NB_SORCIERE = 0

DEFAULT_NB_CHASSEUR = 0

DEFAULT_NB_ANGE = 0

###
